#ifndef PORT_CFG_H_
#define PORT_CFG_H_

#define PORT_DEV_ERROR_DETECT               STD_OFF
#define PORT_SET_PIN_DIRECTION_API          STD_ON
#define PORT_SET_PIN_MODE_API               STD_OFF

#define PORTA_CONFIGURABLE  STD_ON
#define PORTB_CONFIGURABLE  STD_ON
#define PORTC_CONFIGURABLE  STD_ON
#define PORTD_CONFIGURABLE  STD_ON
#define PORTE_CONFIGURABLE  STD_ON
#define PORTF_CONFIGURABLE  STD_OFF
#define PORTK_CONFIGURABLE  STD_ON
#define PORTH_CONFIGURABLE  STD_ON
#define PORTJ_CONFIGURABLE  STD_ON
#define PORTL_CONFIGURABLE  STD_OFF
#define PORTM_CONFIGURABLE  STD_OFF
#define PORTP_CONFIGURABLE  STD_ON
#define PORTR_CONFIGURABLE  STD_OFF
#define PORTS_CONFIGURABLE  STD_ON
#define PORTT_CONFIGURABLE  STD_OFF
#define PORT_AN00_07_CONFIGURABLE  STD_ON
#define PORT_AN08_15_CONFIGURABLE  STD_ON
#define PORT_AN16_23_CONFIGURABLE  STD_ON
#define PORT_AN24_31_CONFIGURABLE  STD_OFF


#include "Port_Types.h"


#endif
