#ifndef __STORAGE_M_CFG_H__
#define __STORAGE_M_CFG_H__

#include "StorageM_Types.h"


#define STORAGEM_DEV_ERROR_DETECT           STD_OFF

#define PARTITION_NUM                       3U

#define STORAGEM_PARTITION_TYPE_RESERVED    0x0U
#define STORAGEM_PARTITION_TYPE_DTC         0x1U
#define STORAGEM_PARTITION_TYPE_RECORD      0x2U

#define STORAGEM_FULLCHIP_ID    STORAGEM_PARTITION_ZERO_INDEX_ID_DEF(STORAGEM_PARTITION_TYPE_FULLCHIP)
#define STORAGEM_DTC_ID         STORAGEM_PARTITION_ID_DEF(1U, STORAGEM_PARTITION_TYPE_DTC)
#define STORAGEM_RECORD_ID      STORAGEM_PARTITION_ID_DEF(2U, STORAGEM_PARTITION_TYPE_RECORD)

extern const struct StorageMConfigType StorageMConfig;

#endif
