classdef Diagnosis_ItemType < Simulink.IntEnumType
    % MATLAB enumeration class definition generated from template
    
    enumeration
        DIAGNOSIS_ITEM_CHG_HV(0),
		DIAGNOSIS_ITEM_CALIBRATE_START(0),
		DIAGNOSIS_ITEM_VOLT_START(0),
		DIAGNOSIS_ITEM_DCHG_HV(1),
		DIAGNOSIS_ITEM_CHG_LV(2),
		DIAGNOSIS_ITEM_DCHG_LV(3),
		DIAGNOSIS_ITEM_CHG_HTV(4),
		DIAGNOSIS_ITEM_DCHG_HTV(5),
		DIAGNOSIS_ITEM_CHG_LTV(6),
		DIAGNOSIS_ITEM_DCHG_LTV(7),
		DIAGNOSIS_ITEM_CHG_DTV(8),
		DIAGNOSIS_ITEM_DCHG_DTV(9),
		DIAGNOSIS_ITEM_CHG_DV(10),
		DIAGNOSIS_ITEM_DCHG_DV(11),
		DIAGNOSIS_ITEM_VOLT_STOP(11),
		DIAGNOSIS_ITEM_CHG_HT(12),
		DIAGNOSIS_ITEM_TEMPERATURE_START(12),
		DIAGNOSIS_ITEM_DCHG_HT(13),
		DIAGNOSIS_ITEM_CHG_LT(14),
		DIAGNOSIS_ITEM_DCHG_LT(15),
		DIAGNOSIS_ITEM_CHG_DT(16),
		DIAGNOSIS_ITEM_DCHG_DT(17),
		DIAGNOSIS_ITEM_TEMPERATURE_STOP(17),
		DIAGNOSIS_ITEM_DC_CHG_OC(18),
		DIAGNOSIS_ITEM_CURRENT_START(18),
		DIAGNOSIS_ITEM_AC_CHG_OC(19),
		DIAGNOSIS_ITEM_FB_OC(20),
		DIAGNOSIS_ITEM_DCHG_OC(21),
		DIAGNOSIS_ITEM_SP_OC(22),
		DIAGNOSIS_ITEM_CURRENT_STOP(22),
		DIAGNOSIS_ITEM_HSOC(23),
		DIAGNOSIS_ITEM_SOC_START(23),
		DIAGNOSIS_ITEM_LSOC(24),
		DIAGNOSIS_ITEM_SOC_STOP(24),
		DIAGNOSIS_ITEM_LEAK(25),
		DIAGNOSIS_ITEM_CHG_HEAT_HT(26),
		DIAGNOSIS_ITEM_DCHG_HEAT_HT(27),
		DIAGNOSIS_ITEM_CHG_HEAT_DT(28),
		DIAGNOSIS_ITEM_DCHG_HEAT_DT(29),
		DIAGNOSIS_ITEM_CHG_HEAT_TIMEOUT(30),
		DIAGNOSIS_ITEM_DCHG_HEAT_TIMEOUT(31),
		DIAGNOSIS_ITEM_CHG_HEAT_OC(32),
		DIAGNOSIS_ITEM_DCHG_HEAT_OC(33),
		DIAGNOSIS_ITEM_SOC_JUMP(34),
		DIAGNOSIS_ITEM_SUPPLY_VOL_LOW(35),
		DIAGNOSIS_ITEM_CHG_POLE_HT(36),
		DIAGNOSIS_ITEM_DCHG_POLE_HT(37),
		DIAGNOSIS_ITEM_CHG_POLE_DT(38),
		DIAGNOSIS_ITEM_DCHG_POLE_DT(39),
		DIAGNOSIS_ITEM_CHG_CUR_FAULT(40),
		DIAGNOSIS_ITEM_CALIBRATE_STOP(40),
		DIAGNOSIS_ITEM_VOLT_LINE(128),
		DIAGNOSIS_ITEM_NONE_CALIBRATE_START(128),
		DIAGNOSIS_ITEM_LINE_START(128),
		DIAGNOSIS_ITEM_TEMP_LINE(129),
		DIAGNOSIS_ITEM_LINE_STOP(129),
		DIAGNOSIS_ITEM_INTER_COMM(130),
		DIAGNOSIS_ITEM_CHGSCKTMP_DC_POSITIVE(131),
		DIAGNOSIS_ITEM_CHGSCKTMP_START(131),
		DIAGNOSIS_ITEM_CHGSCKTMP_DC_NEGATIVE(132),
		DIAGNOSIS_ITEM_CHGSCKTMP_AC_AL(133),
		DIAGNOSIS_ITEM_CHGSCKTMP_AC_BN(134),
		DIAGNOSIS_ITEM_CHGSCKTMP_AC_C(135),
		DIAGNOSIS_ITEM_CHGSCKTMP_STOP(135),
		DIAGNOSIS_ITEM_CHARGER_COMM(136),
		DIAGNOSIS_ITEM_VCU_COMM(137),
		DIAGNOSIS_ITEM_FULL_CHARGE(138),
		DIAGNOSIS_ITEM_CHGSCKTMP_ABNORMAL(139),
		DIAGNOSIS_ITEM_PRECHARGE_FAILURE(140),
		DIAGNOSIS_ITEM_CURRENT_ABNORMAL(141),
		DIAGNOSIS_ITEM_BMS_INIT_FAILURE(142),
		DIAGNOSIS_ITEM_HVIL_ABNORMAL(143),
		DIAGNOSIS_ITEM_RELAY_ABNORMAL(144),
		DIAGNOSIS_ITEM_HEAT_FAULT(145),
		DIAGNOSIS_ITEM_CC2_CONNECT_FAULT(146),
		DIAGNOSIS_ITEM_CC_CONNECT_FAULT(147),
		DIAGNOSIS_ITEM_CP_CONNECT_FAULT(148),
		DIAGNOSIS_ITEM_HEAT_TEMP_LINE_FAULT(149),
		DIAGNOSIS_ITEM_POLE_TEMP_LINE_FAULT(150),
		DIAGNOSIS_ITEM_EL_FAULT(151),
		DIAGNOSIS_ITEM_DOUBLE_CHG_CONNECT_FAULT(152),
		DIAGNOSIS_ITEM_ACT_BAT_NUM(153),
		DIAGNOSIS_ITEM_ACT_TMP_NUM(154),
		DIAGNOSIS_ITEM_CRASH_FAULT(155),
		DIAGNOSIS_ITEM_NONE_CALIBRATE_STOP(156),
		DIAGNOSIS_ITEM_MAX_NUM(157),
		DIAGNOSIS_ITEM_INVALID_INDEX(255)
    end

    methods (Static)
        
        function defaultValue = getDefaultValue()
            % GETDEFAULTVALUE  Returns the default enumerated value.
            %   If this method is not defined, the first enumeration is used.
            defaultValue = Diagnosis_ItemType.DIAGNOSIS_ITEM_CHG_HV;
        end

        function dScope = getDataScope()
            % GETDATASCOPE  Specifies whether the data type definition should be imported from,
            %               or exported to, a header file during code generation.
            dScope = 'Imported';
        end

        function desc = getDescription()
            % GETDESCRIPTION  Returns a description of the enumeration.
            desc = '';
        end
        
        function headerFile = getHeaderFile()
            % GETHEADERFILE  Specifies the name of a header file. 
            headerFile = 'Diagnosis_Cfg.h';
        end
        
        function flag = addClassNameToEnumNames()
            % ADDCLASSNAMETOENUMNAMES  Indicate whether code generator applies the class name as a prefix
            %                          to the enumeration.
            flag = false;
        end

    end

end
