#ifndef MODULES_H_
#define MODULES_H_

#define MODULE_ID_HLSS          128U
#define MODULE_ID_HALL          129U
#define MODULE_ID_UART          130U
#define MODULE_ID_AT24          131U
#define MODULE_ID_DRV8844       132U
#define MODULE_ID_EL            133U
#define MODULE_ID_HWDIAGNOSIS   134U
#define MODULE_ID_BRIDGEINSU    135U
#define MODULE_ID_HV            136U
#define MODULE_ID_GB32960       137U
#define MODULE_ID_EEEPROM       138U
#define MODULE_ID_J1939TP       139U
#define MODULE_ID_DRV8872       140U

//bms_rte
#define MODULE_ID_INTERNALCOMM  150U
#define MODULE_ID_BALANCEM      151U
#define MODULE_ID_CHARGECONNECTM    152U
#define MODULE_ID_CHGSCKTMPM    153U
#define MODULE_ID_DIAGNOSIS     154U
#define MODULE_ID_CURRENTM      155U
#define MODULE_ID_ANALOGINPUT   156U
#define MODULE_ID_PARAMETERM    157U
#define MODULE_ID_DIGITALINPUT  158U
#define MODULE_ID_DEVICEINFO    159U
#define MODULE_ID_SOC           160U
#define MODULE_ID_SOCCALIB      161U
#define MODULE_ID_RELAYM        162U
#define MODULE_ID_CHARGERCOMM   163U
#define MODULE_ID_CHARGERCOMM_GB    164U
#define MODULE_ID_CHARGERCOMM_USER  165U
#define MODULE_ID_STORAGEM      166U
#define MODULE_ID_CHARGERCOMM_USER_MESSAGES     167U
#define MODULE_ID_VCUCOMM       168U
#define MODULE_ID_VCUCOMM_MESSAGES  169U
#define MODULE_ID_USERSTRATEGY  170U
#define MODULE_ID_POWERM        171U
#define MODULE_ID_EXTERNCANCOMM 172U
#define MODULE_ID_EXTERNCANCOMM_GB 173U

#endif
